Fix NoSuchMethodError (#8)
- Added compatibility test to check for case where template is being used.
- Added Gradle 3.5, 4.0 to test matrix.
- Dropped us of `inputs.file`, ue a getter instead with @InputFile and
  @Optional.